# Generated by Django 6.0.5 on 2026-06-01 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
        ('players', '0003_player_average_player_fifties_player_hundreds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Innings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innings_number', models.IntegerField()),
                ('runs', models.IntegerField(default=0)),
                ('wickets', models.IntegerField(default=0)),
                ('overs', models.FloatField(default=0)),
                ('batting_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.team')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.match')),
            ],
        ),
        migrations.CreateModel(
            name='BowlingScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overs', models.FloatField(default=0)),
                ('maidens', models.IntegerField(default=0)),
                ('runs', models.IntegerField(default=0)),
                ('wickets', models.IntegerField(default=0)),
                ('economy', models.FloatField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
                ('innings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.innings')),
            ],
        ),
        migrations.CreateModel(
            name='BattingScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs', models.IntegerField(default=0)),
                ('balls', models.IntegerField(default=0)),
                ('fours', models.IntegerField(default=0)),
                ('sixes', models.IntegerField(default=0)),
                ('strike_rate', models.FloatField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
                ('innings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.innings')),
            ],
        ),
    ]
