# Generated by Django 6.0.5 on 2026-06-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_player_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='average',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='fifties',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='hundreds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='strike_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='wickets',
            field=models.IntegerField(default=0),
        ),
    ]
